language: cpp
compiler: g++
sudo: true

os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libxrandr2
script:
    - mkdir build
    - cd build
    - cmake -DBUILD_SHARED_LIBS=OFF -DGLFW_INSTALL_ENABLE=OFF ..
    - make -j
