language: cpp
before_install:
  - sudo apt-get update -q
#compiler: gcc g++
sudo: true
# install:
#  - libxrandr
#  - libwrandr
os: linux 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      libxrandr2
      libwrandr-dev
      libudev-dev
env:
  - TRAVIS_BUILD_GPG_KEYS_URL=gpg_keys.json
    
script:
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DGLM_TEST_ENABLE=OFF -DGLAD_INSTALL=OFF -DGLAD_LOADER=ON -DUSE_SFML=ON .. 
  - cmake --build .
